// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-posts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabasePublic() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published blog posts, most recent first. Optionally filter by tag or category. Returns titles, slugs, excerpts, and metadata (not full content).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of posts to return (default 20)."),
    tag: z.string().optional().describe("Only return posts that include this tag."),
    category: z.string().optional().describe("Only return posts in this category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, tag, category }) => {
    const supabase = supabasePublic();
    let query = supabase.from("blog_posts").select("id, title, slug, excerpt, category, tags, read_time, created_at, updated_at").eq("published", true).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (tag) query = query.contains("tags", [tag]);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-post.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabasePublic2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Get a single published blog post by its slug, including the full markdown content.",
  inputSchema: {
    slug: z2.string().min(1).describe("The slug of the blog post to fetch.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = supabasePublic2();
    const { data, error } = await supabase.from("blog_posts").select(
      "id, title, slug, excerpt, content, category, tags, cover_image, read_time, created_at, updated_at"
    ).eq("published", true).eq("slug", slug).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: `No published post found for slug "${slug}".` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/search-posts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabasePublic3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_posts_default = defineTool3({
  name: "search_blog_posts",
  title: "Search blog posts",
  description: "Search published blog posts by keyword across title, excerpt, and content. Returns matching posts with metadata (not full content).",
  inputSchema: {
    query: z3.string().min(1).describe("Keyword or phrase to search for."),
    limit: z3.number().int().min(1).max(50).optional().describe("Maximum number of results to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = supabasePublic3();
    const term = `%${query}%`;
    const { data, error } = await supabase.from("blog_posts").select("id, title, slug, excerpt, category, tags, read_time, created_at, updated_at").eq("published", true).or(`title.ilike.${term},excerpt.ilike.${term},content.ilike.${term}`).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "bayu-portfolio-mcp",
  title: "Bayu Dwi Darmawan Portfolio MCP",
  version: "0.1.0",
  instructions: "Tools for reading Bayu Dwi Darmawan's portfolio blog. Use `list_blog_posts` to browse published posts, `search_blog_posts` to find posts by keyword, and `get_blog_post` to read a full post by slug.",
  tools: [list_posts_default, search_posts_default, get_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
